### ISSUE TITLE
로그인 버튼 label -> "이메일로 로그인" 으로 변경해야 할지 않을까 합니다

### ISSUE THREAD

**Issue by Poxios** [Portunecookie/Tito-FrontEnd#35]
![image](https://github.com/user-attachments/assets/15249e5e-48aa-474d-bf03-a48fd045d0f4)

대부분의 사용자들이 oauth로 로그인 할 것으로 예상되는데,
oauth 방식이 아닌 이메일 로그인의 경우 로그인 버튼의 디자인이 위 oauth 로그인 버튼들과 일관성이 있어야하지 않을까요?

추가로, "카카오 로그인" 대신 "카카오로 시작하기" 이런 단어를 쓰는게 낫지 않을까 싶어요

**Comment by zieunshin** [comment]
' ~ 로 시작하기' 로 고치는 건 좋은 것 같아요 

고민인 점은, 해당 까만 로그인 버튼은 앱 내에서 회원가입을 진행한 경우라서 차별을 둔 것 같은데 그래도 버튼의 일관성이 있는게 나을까요?

**Comment by Poxios** [comment]
> ' ~ 로 시작하기' 로 고치는 건 좋은 것 같아요
> 
> 고민인 점은, 해당 까만 로그인 버튼은 앱 내에서 회원가입을 진행한 경우라서 차별을 둔 것 같은데 그래도 버튼의 일관성이 있는게 나을까요?

밑 "로그인"버튼은 위 OAuth 버튼 세개에 비해서 눌리는 빈도가 적은 버튼인데 가장 눈에 잘 띄게 되어 있어 그랬어요!
근데 UI 상 의미가 있을 수도 있으니 월요일 회의때 이어서 얘기해봅시다~ 노션에 넣어놓을게요
