### ISSUE TITLE
메인화면 확장

### ISSUE THREAD

**Issue by Poxios** [Portunecookie/Tito-FrontEnd#79]
최초 로그인 화면이 위아래로 잘리는데 이거 수정 필요
![image](https://github.com/user-attachments/assets/982c0c9a-846a-4303-aefc-771c5ef0c0eb)

그리고, 밑 로그인 창 색 배합 어떠신지
![image](https://github.com/user-attachments/assets/d18a5372-eb01-4aac-a784-6720d13d4383)

**Comment by zieunshin** [comment]
네 ! 수정중에 있습니다! 조금만 기다려주세요 폭시님!

**Comment by zieunshin** [comment]
전체화면 적용됬습니다 !

**Comment by zieunshin** [comment]
![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-28 at 12 22 17](https://github.com/user-attachments/assets/21d535cf-a1f1-4224-8056-a25030132078)
![Simulator Screenshot - iPhone 15 Pro Max - 2024-08-28 at 12 22 03](https://github.com/user-attachments/assets/f9b4c8ad-62c5-4e99-92c8-1e330dc454c5)
